# status
set -g status-position bottom
set -g status-interval 1
set -g escape-time 10

# start index from 1
set -g base-index 1
setw -g pane-base-index 1

# terminal colors
set -g extended-keys on
set -sag terminal-features 'xterm*:extkeys'
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",$TERM:Tc"

set -g focus-events on
set -g renumber-windows on

# change prefix
unbind C-b
unbind C-s
set -g prefix C-s
bind-key C-s send-prefix

# bind keys
bind -n M-C-k choose-tree -Z
bind -n M-'[' previous-window
bind -n M-']' next-window
bind -n M-',' swap-window -t -1\; select-window -t -1
bind -n M-'.' swap-window -t +1\; select-window -t +1
bind -n C-M-'h' resize-pane -L 5
bind -n C-M-'l' resize-pane -R 5
bind -n C-M-'k' resize-pane -U 2
bind -n C-M-'j' resize-pane -D 2
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind C-'h' select-pane -L
bind C-'j' select-pane -D
bind C-'k' select-pane -U
bind C-'l' select-pane -R

bind x killp

set -g mouse on

# reload config file
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# This is by the help of chatGPT :p
set -g status-interval 1
set -g status-right '#[bg=default]#{pane_current_path}'
set -g status-style 'bg=default'

set -g allow-rename off

# Style for window
set -g window-status-current-style fg="blue"
set -g window-status-current-format "#I: #W"
set -g window-status-format "#I: #W"
